# -*- coding: utf-8 -*-
"""Document_verification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vXgCck5eXNUeCzSpVD_wd_orK8HI4KV
"""

!pip install pytesseract

!sudo apt-get install tesseract-ocr

import pytesseract
from PIL import Image, ImageFilter, ImageEnhance
import matplotlib.pyplot as plt
import os
import numpy as np
import cv2
import re

img_path="/content/drive/MyDrive/Mummy aadhar.jpg"
img=cv2.imread(img_path)
img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

h,w,c=img.shape
if w>1000:
  new_w=1000
  ar = w/h
  new_h=int(new_w/ar)
  img=cv2.resize(img,(new_w,new_h),interpolation=cv2.INTER_AREA)
x, y, w, h = 250, 120, 550, 410

# Crop the image to the defined ROI
roi = img[y:y+h, x:x+w]
# plt.imshow(roi)
def thresholding(image):
  img_gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
  ret,thresh = cv2.threshold(img_gray,120, 255, cv2.THRESH_BINARY)
  # plt.imshow(thresh)
  return thresh

thresh_img=thresholding(img)

text = pytesseract.image_to_string(thresh_img, lang='eng+guj')

# Print the extracted text for verification
#print("Extracted Text:\n", text)
lines = text.strip().split('\n')

# Extract the name as the second line of the text
name = lines[2].strip() if len(lines) > 1 else "Name not found"


# Regex patterns to identify DOB and other details
dob_pattern = re.compile(r'DOB\s*:\s*(\d{2}/\d{2}/\d{4})')
gender_pattern = re.compile(r'(Male|Female)', re.IGNORECASE)
aadhar_pattern = re.compile(r'(\d{4}\s\d{4}\s\d{4})')

# Extract DOB, Gender, and Aadhaar Number
dob_match = dob_pattern.search(text)
gender_match = gender_pattern.search(text)
aadhar_match = aadhar_pattern.search(text)

# Print the extracted details
if name:
    print("Name:", name)
if dob_match:
    print("Date of Birth:", dob_match.group(1))
if gender_match:
    print("Gender:", gender_match.group(1))
if aadhar_match:
    print("Aadhaar Number:", aadhar_match.group(1))

"""EASY OCR"""

!pip install easyocr

import cv2
import easyocr
import re

img_path = "/content/drive/MyDrive/pappa_aadhar.jpg"
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Resize if width is greater than 1000
h, w, c = img.shape
if w > 1000:
    new_w = 1000
    ar = w / h
    new_h = int(new_w / ar)
    img = cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_AREA)

# Define the Region of Interest (ROI)
x, y, w, h = 250, 120, 550, 410
roi = img[y:y+h, x:x+w]

# Grayscale and thresholding function (Optional for EasyOCR)
def thresholding(image):
    img_gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(img_gray, 120, 255, cv2.THRESH_BINARY)
    return thresh

# Optionally apply thresholding
thresh_img = thresholding(img)

# Initialize EasyOCR Reader
reader = easyocr.Reader(['en'])  # English and Gujarati languages

# Perform text extraction using EasyOCR
result = reader.readtext(thresh_img, detail=0)  # detail=0 gives plain text

# Combine result into a single string
text = '\n'.join(result)

# Print the extracted text
print("Extracted Text:\n", text)

# Split the text into lines
import re

# Split the text into lines
lines = text.strip().split('\n')

# Extract the name by checking the second line, and cleaning up whitespace or noise
name = None
if len(lines) > 1:
    # Assuming that the name is usually on the second line
    possible_name = lines[1].strip()
    # Check if the extracted line has any unexpected non-name characters (you can expand this check)
    if re.match(r'^[A-Za-z\s]+$', possible_name):
        name = possible_name
    else:
        name = "Name not found"
else:
    name = "Name not found"

# Regex patterns to identify DOB and other details
dob_pattern = re.compile(r'(\d{2}/\d{2}/\d{4})')  # This will capture any date in dd/mm/yyyy format
gender_pattern = re.compile(r'(Male|Female)', re.IGNORECASE)
aadhar_pattern = re.compile(r'\b\d{4}\s\d{4}\s\d{4}\b')

# Extract DOB, Gender, and Aadhaar Number
dob_match = dob_pattern.search(text)
gender_match = gender_pattern.search(text)
aadhar_match = aadhar_pattern.search(text)

# Print the extracted details
if name:
    print("Name:", name)

# Ensure that the DOB is in valid format and found
if dob_match:
    print("Date of Birth:", dob_match.group(1))
else:
    print("Date of Birth not found")

# Print gender if found
if gender_match:
    print("Gender:", gender_match.group(1))

for line in lines:
    match = aadhar_pattern.search(line)
    if match:
        aadhar_number = match.group(0)  # Extract the full Aadhaar number
        break  # Stop after finding the first full match
if aadhar_number:
    print("Aadhaar Number:", aadhar_number)
else:
    print("Aadhaar Number not found")